language: java
jdk:
  - oraclejdk8
script:
  - ./ceylonb compile
  - ./ceylonb test examples.fr.minibilles.cli
cache:
  directories:
    - $HOME/.ceylon/cache/
    - $HOME/.ceylon/dists/
notifications:
  slack: minibilles:2dXpzGnWFnhbU9WrAEwIPn7g
